version: 0.0
os: linux

files:
  - source: ./build # 인스턴스에 복사할 파일 또는 디렉터리 appspec.yml 기준 상대경로
    destination: /var/www/deploySource # 인스턴스 내 파일이 복사되는 위치
    overwrite: yes # 동일 파일 있을경우 덮어쓰기 여부
permissions: # 복사된 파일 권한 적용
  - object: /var/www/deploySource
    owner: centos
    group: centos
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/backup.sh # 스크립트 위치: application root 기준
      timeout: 180 # 스크립트 실행에 허용되는 최대 시간. 초과시 이벤트 실패
      runas: root
  AfterInstall:
    - location: scripts/movefile.sh
      timeout: 180
      runas: root