version: 0.0
os: linux

files:
  - source: /
    destination: /usr/local/lib/apache-tomcat-8.5.65/deploySource
    overwrite: yes
permissions:
  - object: /usr/local/lib/apache-tomcat-8.5.65/deploySource
    owner: centos
    group: centos
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/movefile.sh
      timeout: 180
      runas: root